### ISSUE TITLE
Script fetch

### ISSUE THREAD

**Issue by ekoeryanto** [lakuapik/js-holiday-id#1]
Ini official atau hasil scrawl?

hatur nuhun.

**Comment by lakuapik** [comment]
utk script fetch memang tidak ada. waktu itu saya hanya copy paste dari website https://www.bi.go.id/id/ruang-media/agenda/kalender-hari-libur ke xls. lalu di convert ke csv. lalu di convert lagi ke json. begitu wkwk.

**Comment by ekoeryanto** [comment]
:rofl: 
udah ah bikin sendiri https://github.com/ekoeryanto/liburan

**Comment by lakuapik** [comment]
wih mantap :+1:
